[package]
authors = ['Luuk van der Duim <luukvanderduim@gmail.com>']
edition = '2018'
name = 'xcb-global-hotkey-example'
version = '0.1.0'

[dependencies]

[dependencies.xcb]
features = [  'xkb' ]
version = "0.8.2"



