[package]
authors = ['Luuk van der Duim <luukvanderduim@gmail.com>']
edition = '2018'
name = "global-hotkey-example"
version = "0.2.0"

[dependencies]
x11rb = { version = "0.7.0", features = ["xkb"]} 
